### ISSUE TITLE
Question on inclusion of BitcoinJS-Lib

### ISSUE THREAD

**Issue by ghost** [mappum/blockchain-spv#14]
Hey there

What's the reason to add BitcoinJS into the mix with your webcoin refactoring, instead of sticking entirely with Bitcore?

e.g.
https://github.com/mappum/webcoin/blob/master/lib/blockStore.js#L90

becomes..

https://github.com/mappum/blockchain-spv/blob/master/src/blockStore.js#L93

Thanks!

**Comment by mappum** [comment]
_Sorry for the late response_

I made the decision to switch because I am a big fan of the minimalism of BitcoinJS. The code itself is much smaller, which reduces the bug/attack surface. Overall the differences are mostly trivial, but I was planning on making some big changes to Webcoin anyway so migrating from Bitcore to BitcoinJS was pretty low-effort.

Both are great libraries and I'm thankful for the hard work that has gone into them.
